# Site settings
site: Ephesus
title: Urav.in 
keywords: ephesus, blog
description: >-
  Urav.in 
lang: en-US
timezone:  Europe/Istanbul
repo: https://github.com/gauravbansal74/Ephesus # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Gaurav Kumar
  bio: Computer Engineer @pardinus <br> Founder @zaqa <br> Open Source /#linux
  picture: assets/images/profile.jpg 
  github: gauravbansal74 # github username
  twitter: gauravbansal74 # twitter username
  facebook: gauravbansal74 # facebook username
  instagram: gauravbansal74 # instagram username
  youtube: https://www.youtube.com/channel/UCMmAto-wxBootXN91AzBiDg # youtube username
  linkedin: hakantorun # linkedin username
  email: your-email@email.com # email adress


# URL settings
url: "https://gauravbansal74.github.io/" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false